version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        REACT_APP_API_HOST: ${REACT_APP_API_HOST}
        REACT_APP_CLIENT_ID: ${BLOCKPASS_CLIENT_ID}
        REACT_APP_SECRET_ID: ${BLOCKPASS_SECRET_ID}
        BLOCKPASS_BASE_URL: ${BLOCKPASS_BASE_URL}
   
    command: npm run prod
    ports:
      - "${PORT}:3000"
      
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DELOY_SECRET_KEY: ${DELOY_SECRET_KEY}
      MONGODB_URI: ${MONGODB_URI}
      BLOCKPASS_BASE_URL: ${BLOCKPASS_BASE_URL}
      BLOCKPASS_CLIENT_ID: ${BLOCKPASS_CLIENT_ID}
      BLOCKPASS_SECRET_ID: ${BLOCKPASS_SECRET_ID}