version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
   
    command: npm run prod  
    ports:
      - "${PORT}:3000"

    restart: always
    
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DELOY_SECRET_KEY: ${DELOY_SECRET_KEY}
      MONGODB_URI: ${MONGODB_URI}
      BLOCKPASS_BASE_URL: ${BLOCKPASS_BASE_URL}
      BLOCKPASS_CLIENT_ID: ${BLOCKPASS_CLIENT_ID}
      BLOCKPASS_SECRET_ID: ${BLOCKPASS_SECRET_ID}
      KYC_RECORD_EXPIRED_AFTER_MS: ${KYC_RECORD_EXPIRED_AFTER_MS}